version: '3.8'

services:
  backend:
    platform: linux/amd64
    build: ./backend
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENV=development

  frontend:
    build: ./frontend
    ports:
      - "33123:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
